[tool.poetry]
name = "sodoku"
version = "0.1.0"
description = ""
authors = ["Gergo Kanyogh <kgergo1713@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pygame = "^2.6.1"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
